[global]
# Development mode
developmentMode = false

[server]
# Server configuration
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
port = 8501

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
caching = true
displayEnabled = true
showErrorDetails = false

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Logger configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Deprecation warnings
showfileUploaderEncoding = false
showPyplotGlobalUse = false
